### PR TITLE
NetCDF Projection Conversions

### LINKED ISSUE #14: Interest in NetCDF projection handling?
If you'd like the gridmapping and projection code from here: https://github.com/USGS-R/ncdfgeom/tree/master/R, I'd be more than happy to move it to `ncmeta` and update to match the data constructs used here. It is by no means perfect, but I've gotten a lot of mileage out of it and it is a good starting point for general parsing and conversion of the CF [`grid_mapping`](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch05s06.html) construct.

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
This fixes #14 

I am terrible at naming, so please look at function names and suggest what might be more in line with the package vision. Happy to refactor or find a better home for these as you see fit.

### CODE REVIEW

**Comment by mdsumner** [comment]
I was expecting to see a "nc_grid_mapping" function that was *variable specific*, because there can be more than one to a file/source. This "nc_grid_mapping_atts" doesn't pick up the names in a source I have , specifically 

```
nc_grid_mapping_atts(f)
# A tibble: 4 x 2
  name                        value    
  <chr>                       <list>   
1 grid_mapping_name           <chr [1]>
2 semi_major_axis             <dbl [1]>
3 inverse_flattening          <dbl [1]>
4 longitude_of_prime_meridian <dbl [1]>
Warning message:
In nc_grid_mapping_atts.data.frame(nc_atts(x)) :
  No variables with a grid mapping found.
 Defaulting to WGS84 Lon/Lat
```

but still I have to explore this some more. I'll try to find a shareable file that has this behaviour (this one is 9Gb...)

**Comment by dblodgett-usgs** [comment]
That's because there's no `grid_mapping` attribute or variable.

I've never seen a file that uses multiple grid_mappings, but it looks like that _is_ the intention of cf. http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch05s06.html

I'll work that in to this. So nc_grid_mapping_atts will optionally take a variable name. In the case that you don't pass a variable name it may return multiple grid_mappings.

**Comment by mdsumner** [comment]
Oh sheesh, sorry - showing my ignorance. I was thinking this was the *coordinates* attribute, and little more. I'll have a closer look, thanks!

**Comment by mdsumner** [comment]
I don't have a problem with the names as they are!

**Pull request merged**
